# Site settings
title: little dragoner's blog
email: zx547732454@live.com
description: > # this means to ignore newlines until "baseurl:"
  他们的爱，他们的恨，他们的嫉妒，都早消灭了。在日光之下所行的一切事上，
  他们永不再有份了。
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://xiaojinlong.org" # the base hostname & protocol for your site
github_username:  syca0516
# Build settings
markdown:    kramdown
highlighter: rouge
lsi:         false
excerpt_separator: "\n\n"
incremental: false


kramdown:
  auto_ids:       true
  footnote_nr:    1
  entity_output:  as_char
  toc_levels:     1..6
  smart_quotes:   lsquo,rsquo,ldquo,rdquo
  input:          GFM
  hard_wrap:      false
  footnote_nr:    1